version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: dkrcomp-mongo
        image: mongo
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: bdung
            MONGO_INITDB_DATABASE: trade
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro